version: '3.3'

services:
  sudoku:
    container_name: programming_sudoku
    image: programming/sudoku:latest
    build: .
    ports:
      - '4431:1337'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.2'
          memory: 50M
    healthcheck:
      test: socat - TCP4:localhost:1337 || exit 1
      interval: 60s
      timeout: 2s
      retries: 5
