version: '3.8'

services:

  justbinbash:
    build: .
    ports:
      - '2225:22'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 50M
    healthcheck:
      test: nc localhost 22 || exit 1
      interval: 60s
      timeout: 2s
      retries: 5
