version: '3.8'

services:
  web:
    build: .
    ports:
      - '8883:80'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 50M
    healthcheck:
      test: curl --fail http://127.0.0.1/alive || exit 1
      interval: 60s
      timeout: 2s
      retries: 5
