version: '3.3'

services:

  linux1:
    build: .
    ports:
      - '2221:22'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 50M

